import React, { useState } from 'react';
import { Calendar, Plus, Camera, Image, ShieldAlert, FileText, Check, X, Clock, User, Pencil, Trash2, Paperclip, ChevronLeft, ChevronRight } from 'lucide-react';

export default function DailyLogs({ logs, users, activeUser, onAddLog, onDeleteLog, onEditLog }) {
  const isMonitorRole = activeUser.role === 'admin' || ['Ketua Tim', 'Koordinator', 'Tenaga Administrasi', 'Super Admin'].includes(activeUser.jabatanTim);
  const [isAdding, setIsAdding] = useState(false);
  const [selectedUserFilter, setSelectedUserFilter] = useState(isMonitorRole ? 'Semua' : activeUser.id);
  const [previewImage, setPreviewImage] = useState(null);
  
  const [logPage, setLogPage] = useState(1);
  const [editingLogId, setEditingLogId] = useState(null);
  const [editingLogText, setEditingLogText] = useState('');
  const [editingLogFoto, setEditingLogFoto] = useState('');
  
  const [formData, setFormData] = useState({
    tanggal: new Date().toISOString().split('T')[0],
    aktivitas: '',
    foto: ''
  });

  const formatDateShort = (dateStr) => {
    if (!dateStr) return '-';
    try {
      const d = new Date(dateStr);
      if (isNaN(d.getTime())) return dateStr;
      const dd = String(d.getDate()).padStart(2, '0');
      const mm = String(d.getMonth() + 1).padStart(2, '0');
      const yyyy = d.getFullYear();
      return `${dd}-${mm}-${yyyy}`;
    } catch {
      return dateStr;
    }
  };

  const getDirectImageUrl = (url) => {
    if (!url) return '';
    if (url.startsWith('data:')) return url;
    
    if (url.includes('drive.google.com') || url.includes('docs.google.com') || url.includes('googleusercontent.com')) {
      let fileId = null;
      // Extract from uc?id=...
      const idMatch = url.match(/id=([^&]+)/);
      if (idMatch && idMatch[1]) {
        fileId = idMatch[1];
      } else {
        // Extract from /file/d/...
        const dMatch = url.match(/\/d\/([a-zA-Z0-9-_]+)/);
        if (dMatch && dMatch[1]) {
          fileId = dMatch[1];
        }
      }
      
      if (fileId) {
        return `https://lh3.googleusercontent.com/d/${fileId}?authuser=0`;
      }
    }
    return url;
  };

  const formatActivityText = (text) => {
    if (!text) return '';
    // Format inline ISO strings that might be generated by Google Sheets or forms
    return text.replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z/g, (match) => {
      const d = new Date(match);
      // If it's the Google Sheets 1899 epoch date, it was originally just a Time value
      if (match.startsWith('1899-12-30')) {
        return d.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }) + ' WIB';
      }
      // Otherwise, return a readable date and time
      const dd = String(d.getDate()).padStart(2, '0');
      const mm = String(d.getMonth() + 1).padStart(2, '0');
      const yyyy = d.getFullYear();
      const time = d.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });
      return `${dd}-${mm}-${yyyy} Pukul ${time} WIB`;
    });
  };

  // Client-side image resize & compression using Canvas
  const compressImage = (file, callback) => {
    if (!file.type.startsWith('image/')) return window.showAlert('Hanya berkas gambar yang didukung!');

    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = (event) => {
      const img = new window.Image();
      img.src = event.target.result;
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const MAX_WIDTH = 600;
        const MAX_HEIGHT = 600;
        let width = img.width;
        let height = img.height;

        if (width > height) {
          if (width > MAX_WIDTH) {
            height *= MAX_WIDTH / width;
            width = MAX_WIDTH;
          }
        } else {
          if (height > MAX_HEIGHT) {
            width *= MAX_HEIGHT / height;
            height = MAX_HEIGHT;
          }
        }

        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0, width, height);

        // Compress to JPEG with 0.6 quality
        const dataUrl = canvas.toDataURL('image/jpeg', 0.6);
        callback(dataUrl);
      };
    };
  };

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    if (file.size > 10 * 1024 * 1024) {
      e.target.value = '';
      return window.showAlert('Ukuran file gambar terlalu besar! Maksimal 10MB.');
    }
    compressImage(file, (dataUrl) => {
      setPreviewImage(dataUrl);
      setFormData((prev) => ({ ...prev, foto: dataUrl }));
    });
  };

  const handleEditImageChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    if (file.size > 10 * 1024 * 1024) {
      e.target.value = '';
      return window.showAlert('Ukuran file gambar terlalu besar! Maksimal 10MB.');
    }
    compressImage(file, (dataUrl) => {
      setEditingLogFoto(dataUrl);
    });
  };

  const resetForm = () => {
    setFormData({ tanggal: new Date().toISOString().split('T')[0], aktivitas: '', foto: '' });
    setPreviewImage(null);
    setIsAdding(false);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!formData.aktivitas.trim()) return window.showAlert('Aktivitas harian wajib diisi');

    const newLog = {
      id: `log-${activeUser.id}-${Date.now()}`,
      userId: activeUser.id,
      tanggal: formData.tanggal,
      aktivitas: formData.aktivitas,
      foto: formData.foto,
      createdAt: new Date().toISOString()
    };

    onAddLog(newLog);
    window.showAlert('Log kerja harian berhasil dicatat!');
    setFormData({ tanggal: new Date().toISOString().split('T')[0], aktivitas: '', foto: '' });
    setPreviewImage(null);
    setIsAdding(false);
  };

  const getUserName = (id) => {
    const user = users.find(u => u.id === id);
    return user ? user.nama : 'Anggota Tim';
  };

  const getUserRole = (id) => {
    const user = users.find(u => u.id === id);
    return user ? user.jabatanTim : 'Pelaksana';
  };

  const filteredLogs = logs.filter((log) => {
    if (selectedUserFilter === 'Semua') return true;
    return log.userId === selectedUserFilter;
  }).sort((a, b) => {
    const dateDiff = new Date(b.tanggal) - new Date(a.tanggal);
    if (dateDiff !== 0) return dateDiff;
    const timeA = a.createdAt ? new Date(a.createdAt).getTime() : 0;
    const timeB = b.createdAt ? new Date(b.createdAt).getTime() : 0;
    return timeB - timeA;
  }); // Sort by date desc, then by createdAt desc

  return (
    <div className="space-y-6 animate-fade-in p-6">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div>
          <h2 className="text-xl md:text-2xl font-semibold text-slate-100 flex items-center gap-2">
            <Calendar className="w-6 h-6 text-indigo-400" /> Log Kerja Harian
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            {isMonitorRole 
              ? 'Pantau log aktivitas kerja harian seluruh anggota tim pelaksana beserta bukti foto kegiatan.'
              : 'Tulis log jurnal harian Anda untuk melaporkan aktivitas fasilitasi lapangan dilengkapi bukti foto.'}
          </p>
        </div>

        {!isMonitorRole && !isAdding && (
          <button
            onClick={() => setIsAdding(true)}
            className="px-4 py-2 rounded-xl text-sm font-medium bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-2 transition-colors shadow-lg shadow-indigo-600/10 cursor-pointer"
          >
            <Plus className="w-4 h-4" /> Catat Log Harian
          </button>
        )}
      </div>

      {/* Filter Admin */}
      {isMonitorRole && (
        <div className="bg-slate-900/40 backdrop-blur-md border border-slate-800/80 rounded-2xl p-4 flex flex-col sm:flex-row items-center gap-3 select-none">
          <span className="text-xs font-bold uppercase tracking-wider text-slate-500">Filter Pantau Anggota Tim:</span>
          <select
            value={selectedUserFilter}
            onChange={(e) => setSelectedUserFilter(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 text-xs font-semibold text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer"
          >
            <option value="Semua">Semua Anggota Tim</option>
            {users.filter(u => u.jabatanTim !== 'Super Admin').map((u) => (
              <option key={u.id} value={u.id}>{u.nama} ({u.jabatanTim})</option>
            ))}
          </select>
        </div>
      )}

      {/* Form Add Log */}
      {isAdding && (
        <div className="bg-slate-900/50 backdrop-blur-md border border-slate-800 rounded-2xl p-6">
          <h3 className="font-semibold text-slate-200 text-base mb-4 flex items-center gap-2">
            <Plus className="w-4 h-4 text-indigo-400" /> Catat Aktivitas Harian Baru
          </h3>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Tanggal Kegiatan
                </label>
                <input
                  type="date"
                  value={formData.tanggal}
                  onChange={(e) => setFormData({ ...formData, tanggal: e.target.value })}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 text-sm text-slate-100 focus:outline-none focus:border-indigo-500 transition-colors"
                  required
                />
              </div>

              <div className="md:col-span-2">
                <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Bukti Foto Kegiatan (Kompresi Otomatis)
                </label>
                <div className="flex items-center gap-3">
                  <label className="flex items-center gap-2 bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 text-xs font-semibold text-slate-300 hover:text-white cursor-pointer hover:border-slate-700 transition-colors">
                    <Camera className="w-4 h-4 text-slate-400" /> Pilih Foto
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleImageChange}
                      className="hidden"
                    />
                  </label>
                  <span className="text-[10px] text-slate-500 leading-tight">
                    Unggah foto langsung dari kamera/galeri. Sistem otomatis mengompresi gambar.
                  </span>
                </div>
              </div>
            </div>

            {/* Preview and Text Area */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-start">
              <div className="md:col-span-3">
                <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Uraian Aktivitas Pekerjaan
                </label>
                <textarea
                  value={formData.aktivitas}
                  onChange={(e) => setFormData({ ...formData, aktivitas: e.target.value })}
                  placeholder="Deskripsikan pekerjaan Anda hari ini secara mendetail..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2.5 text-xs text-slate-100 focus:outline-none focus:border-indigo-500 transition-colors h-32 resize-none"
                  required
                />
              </div>

              {/* Preview image */}
              <div className="space-y-1">
                <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Preview Foto Bukti
                </label>
                {previewImage ? (
                  <div className="relative border border-slate-800 rounded-xl overflow-hidden aspect-video bg-slate-950 flex items-center justify-center">
                    <img src={previewImage} alt="Bukti harian" className="w-full h-full object-cover" />
                    <button
                      type="button"
                      onClick={() => {
                        setPreviewImage(null);
                        setFormData((prev) => ({ ...prev, foto: '' }));
                      }}
                      className="absolute top-1 right-1 p-1 rounded-full bg-slate-950/80 border border-slate-800 text-slate-400 hover:text-white hover:bg-slate-950 transition-colors cursor-pointer"
                    >
                      <X className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ) : (
                  <div className="border border-dashed border-slate-800 rounded-xl p-6 text-center text-slate-600 text-xs flex flex-col items-center justify-center bg-slate-950/20 aspect-video select-none">
                    <Image className="w-6 h-6 text-slate-700 mb-1" /> Belum ada foto
                  </div>
                )}
              </div>
            </div>

            <div className="pt-3 flex items-center justify-end gap-2 border-t border-slate-800/85">
              <button
                type="button"
                onClick={resetForm}
                className="px-4 py-2 rounded-xl text-sm font-medium text-slate-400 hover:text-slate-200"
              >
                Batal
              </button>
              <button
                type="submit"
                className="px-4 py-2 rounded-xl text-sm font-medium bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1.5 transition-colors shadow-lg"
              >
                <Check className="w-4 h-4" /> Simpan Jurnal Log
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Logs Feed List */}
      <div className="space-y-4">
        {(() => {
          const logsPerPage = 5;
          const totalPages = Math.ceil(filteredLogs.length / logsPerPage) || 1;
          const currentLogPage = Math.min(logPage, totalPages);
          const startIndex = (currentLogPage - 1) * logsPerPage;
          const currentLogs = filteredLogs.slice(startIndex, startIndex + logsPerPage);

          if (filteredLogs.length === 0) {
            return (
              <div className="py-12 text-center text-slate-500 font-semibold border border-dashed border-slate-850 rounded-2xl bg-slate-900/10">
                Belum ada catatan log kerja harian yang terdaftar.
              </div>
            );
          }

          return (
            <>
              {currentLogs.map((log) => {
                const logUser = users.find(u => u.id === log.userId);
                const userName = logUser ? logUser.nama : 'Anggota Tim';
                const userRole = logUser ? logUser.jabatanTim : 'Pelaksana';
                const userInitials = userName.split(' ').map(n => n[0]).slice(0, 2).join('').toUpperCase();
                const isOwner = log.userId === activeUser.id;

                return (
                  <div
                    key={log.id}
                    className="bg-slate-950/20 border border-slate-850/40 rounded-2xl p-4 flex flex-col sm:flex-row justify-between gap-4 hover:border-slate-800 transition-all duration-300"
                  >
                    <div className="flex gap-3 items-start min-w-0 flex-1">
                      {/* User Avatar */}
                      <div className="w-8 h-8 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 font-bold flex items-center justify-center text-xs shrink-0 select-none">
                        {userInitials}
                      </div>
                      
                      <div className="min-w-0 space-y-2 w-full">
                        <div className="flex items-center justify-between gap-2 flex-wrap w-full">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-bold text-slate-200 text-xs truncate">{userName}</span>
                            <span className="text-[9px] font-medium text-slate-500">({userRole})</span>
                            <span className="text-[9px] bg-indigo-500/10 border border-indigo-500/15 text-indigo-400 px-2 py-0.5 rounded-full font-bold flex items-center gap-1 select-none">
                              <Clock className="w-2.5 h-2.5" /> {formatDateShort(log.tanggal)}
                            </span>
                          </div>
                          
                          {isOwner && (
                            <div className="flex items-center gap-1">
                              <button
                                onClick={() => {
                                  setEditingLogId(log.id);
                                  setEditingLogText(log.aktivitas);
                                  setEditingLogFoto(log.foto || '');
                                }}
                                className="p-1.5 text-slate-400 hover:text-indigo-400 hover:bg-indigo-500/10 rounded-lg transition-colors"
                                title="Edit"
                              >
                                <Pencil className="w-3.5 h-3.5" />
                              </button>
                              {onDeleteLog && (
                                <button
                                  onClick={() => {
                                    if (window.confirm('Hapus log ini?')) {
                                      onDeleteLog(log.id);
                                    }
                                  }}
                                  className="p-1.5 text-slate-400 hover:text-rose-400 hover:bg-rose-500/10 rounded-lg transition-colors"
                                  title="Hapus"
                                >
                                  <Trash2 className="w-3.5 h-3.5" />
                                </button>
                              )}
                            </div>
                          )}
                        </div>

                        {editingLogId === log.id ? (
                          <div className="mt-2 space-y-3">
                            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-start">
                              <div className="md:col-span-3">
                                <textarea
                                  value={editingLogText}
                                  onChange={(e) => setEditingLogText(e.target.value)}
                                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 transition-colors resize-none"
                                  rows="4"
                                />
                              </div>
                              <div className="space-y-2">
                                <span className="block text-[10px] font-semibold text-slate-400 uppercase tracking-wider">
                                  Edit Foto Bukti
                                </span>
                                {editingLogFoto ? (
                                  <div className="relative border border-slate-800 rounded-xl overflow-hidden aspect-video bg-slate-950 flex items-center justify-center">
                                    <img src={getDirectImageUrl(editingLogFoto)} alt="Preview edit" crossOrigin={editingLogFoto && editingLogFoto.startsWith('data:') ? undefined : "anonymous"} className="w-full h-full object-cover" />
                                    <button
                                      type="button"
                                      onClick={() => setEditingLogFoto('')}
                                      className="absolute top-1 right-1 p-1 rounded-full bg-slate-950/80 border border-slate-800 text-slate-400 hover:text-white hover:bg-slate-950 transition-colors cursor-pointer"
                                    >
                                      <X className="w-3.5 h-3.5" />
                                    </button>
                                  </div>
                                ) : (
                                  <div className="border border-dashed border-slate-800 rounded-xl p-3 text-center text-slate-655 text-xs flex flex-col items-center justify-center bg-slate-950/20 aspect-video select-none">
                                    <Image className="w-5 h-5 text-slate-700 mb-1" />
                                    <span className="text-[10px]">Belum ada foto</span>
                                  </div>
                                )}
                                <label className="flex items-center justify-center gap-1 bg-slate-900 hover:bg-slate-850 border border-slate-800 hover:border-slate-700 rounded-xl px-3 py-1.5 text-[10px] font-bold text-slate-300 hover:text-white cursor-pointer transition-colors w-full text-center">
                                  <Camera className="w-3.5 h-3.5 text-slate-400" />
                                  <span>Ganti Foto</span>
                                  <input
                                    type="file"
                                    accept="image/*"
                                    onChange={handleEditImageChange}
                                    className="hidden"
                                  />
                                </label>
                              </div>
                            </div>
                            <div className="flex gap-2 justify-end pt-2 border-t border-slate-900/50">
                              <button
                                onClick={() => setEditingLogId(null)}
                                className="px-3 py-1.5 text-xs font-bold text-slate-400 hover:text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors cursor-pointer"
                              >
                                Batal
                              </button>
                              <button
                                onClick={() => {
                                  if (onEditLog && editingLogText.trim()) {
                                    onEditLog(log.id, editingLogText, editingLogFoto);
                                    setEditingLogId(null);
                                  }
                                }}
                                className="px-3 py-1.5 text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-500 rounded-lg transition-colors flex items-center gap-1.5 cursor-pointer"
                              >
                                <Check className="w-3.5 h-3.5" /> Simpan
                              </button>
                            </div>
                          </div>
                        ) : (
                          <p className="text-xs text-slate-300 leading-relaxed font-normal whitespace-pre-line select-text">
                            {formatActivityText(log.aktivitas)}
                          </p>
                        )}
                      </div>
                    </div>

                    {/* Attachment Image Preview */}
                    {log.foto && editingLogId !== log.id && (
                      <div className="w-full sm:w-48 shrink-0 select-none mt-4 sm:mt-0">
                        <div 
                          onClick={() => window.open(log.foto, '_blank')}
                          className="relative border border-slate-800 rounded-xl overflow-hidden aspect-video bg-slate-950 flex items-center justify-center cursor-pointer group/img shadow-md hover:border-indigo-500/50 transition-all duration-300"
                          title="Klik untuk membuka foto asli"
                        >
                          <img 
                            src={getDirectImageUrl(log.foto)} 
                            alt="Bukti kegiatan" 
                            crossOrigin={log.foto && log.foto.startsWith('data:') ? undefined : "anonymous"} 
                            className="w-full h-full object-cover group-hover/img:scale-[1.04] transition-transform duration-500" 
                          />
                          <div className="absolute inset-0 bg-slate-950/40 opacity-0 group-hover/img:opacity-100 flex items-center justify-center transition-opacity duration-300">
                            <span className="text-[10px] font-bold text-white bg-slate-950/80 px-2.5 py-1 rounded-lg border border-slate-800 flex items-center gap-1">
                              <Paperclip className="w-3 h-3" /> Lihat Asli
                            </span>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}

              {/* Pagination Controls */}
              {totalPages > 1 && (
                <div className="flex items-center justify-between pt-4 border-t border-slate-850/50 mt-4">
                  <span className="text-[11px] text-slate-500">
                    Menampilkan <span className="font-bold text-slate-300">{startIndex + 1}</span> hingga <span className="font-bold text-slate-300">{Math.min(startIndex + logsPerPage, filteredLogs.length)}</span> dari <span className="font-bold text-slate-300">{filteredLogs.length}</span> log
                  </span>
                  
                  <div className="flex items-center gap-1 bg-slate-900 border border-slate-800 p-1 rounded-xl">
                    <button
                      onClick={() => setLogPage(p => Math.max(1, p - 1))}
                      disabled={currentLogPage === 1}
                      className="p-1.5 text-slate-400 hover:text-indigo-400 hover:bg-slate-800 disabled:opacity-30 disabled:hover:bg-transparent disabled:hover:text-slate-400 rounded-lg transition-colors"
                    >
                      <ChevronLeft className="w-4 h-4" />
                    </button>
                    
                    <div className="flex items-center gap-1 px-1">
                      {Array.from({ length: totalPages }).map((_, i) => (
                        <button
                          key={i}
                          onClick={() => setLogPage(i + 1)}
                          className={`w-7 h-7 rounded-lg text-[10px] font-bold transition-colors ${
                            currentLogPage === i + 1
                              ? 'bg-indigo-500 text-white'
                              : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'
                          }`}
                        >
                          {i + 1}
                        </button>
                      ))}
                    </div>

                    <button
                      onClick={() => setLogPage(p => Math.min(totalPages, p + 1))}
                      disabled={currentLogPage === totalPages}
                      className="p-1.5 text-slate-400 hover:text-indigo-400 hover:bg-slate-800 disabled:opacity-30 disabled:hover:bg-transparent disabled:hover:text-slate-400 rounded-lg transition-colors"
                    >
                      <ChevronRight className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              )}
            </>
          );
        })()}
      </div>

    </div>
  );
}
